name: ozone_utils_dart
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1'

dependencies:
  http: ^0.12.2
  gobl_utils_dart:
    git: git://github.com/silassare/gobl_utils_dart

dev_dependencies:
  pedantic: ^1.9.0
